---
abstract: 'Bulk load records into PostgreSQL'
author:
  - 'Chris Travers <chris.travers@gmail.com>'
build_requires:
  Test::More: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PGObject-Util-BulkLoad
no_index:
  directory:
    - t
    - inc
requires:
  DBD::Pg: 0
  DBI: 0
  Memoize: 0
  Text::CSV: 0
  Try::Tiny: 0
  perl: 5.006
resources:
  repository: https://github.com/einhverfr/PGObject-Util-BulkLoad.git
version: 0.03
